name: Update Previews
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  updatePreview:
    name: Update Preview
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: action
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    # Install Node 15
    - uses: actions/setup-node@v1
      with:
        node-version: 15
    - name: Cache Dependencies
      uses: egordm/gha-yarn-node-cache@v1
    - name: Install Dependencies
      uses: Jaid/action-npm-install@v1.2.4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
    - name: Run Script
      uses: aa-forks/puppeteer-headful@master
      with:
        args: npm start
      env: 
        CI: 'true'
        DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
        DISCORD_GUILD_CHANNEL_ID: ${{ secrets.DISCORD_GUILD_CHANNEL_ID }}
        DISCORD_USER_MODAL_ID: ${{ secrets.DISCORD_USER_MODAL_ID }}
        DISCORD_DM_ID: ${{ secrets.DISCORD_DM_ID }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff-index --quiet HEAD || git commit -m "Update Preview" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
