name: Update Previews
on:
  schedule:
    - cron: "0 18 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  updatePreview:
    name: Update Preview
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    # Install Node 15
    - uses: actions/setup-node@v1
      with:
        node-version: 15
    - name: Cache Dependencies
      uses: egordm/gha-yarn-node-cache@v1
    - name: Install Dependencies
      uses: Jaid/action-npm-install@v1.2.4
    - name: Run Script
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
      with:
        args: npm start

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update Preview" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}